In [1]:
import os
import sys

sys.path.append(os.path.dirname(os.getcwd()))

from src.load_covid19 import load_clean_covid19
import pandas as pd

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/philipp/.kaggle/kaggle.json'

In [2]:
df = load_clean_covid19()

Dataset already exists at /home/philipp/Dokumente/Master_Data_Science_Fernuni_Hagen/Projektpraktikum_Web_Science/covid-19-risiko-erkennung/src/../data/raw/covid19-dataset. Skipping download.
Saving clean dataset to: /home/philipp/Dokumente/Master_Data_Science_Fernuni_Hagen/Projektpraktikum_Web_Science/covid-19-risiko-erkennung/data/interim/covid-data-clean.csv
Saved
Loading clean dataset from: /home/philipp/Dokumente/Master_Data_Science_Fernuni_Hagen/Projektpraktikum_Web_Science/covid-19-risiko-erkennung/data/interim/covid-data-clean.csv

In [3]:
df

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,COPD,...,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU,DIED
0,2,1,female,returned home,<NA>,True,65,False,False,False,...,False,True,False,False,False,False,False,3,<NA>,True
1,2,1,male,returned home,<NA>,True,72,<NA>,False,False,...,False,True,False,False,True,True,False,5,<NA>,True
2,2,1,male,hospitalization,True,False,55,<NA>,True,False,...,False,False,False,False,False,False,False,3,False,True
3,2,1,female,returned home,<NA>,False,53,False,False,False,...,False,False,False,False,False,False,False,7,<NA>,True
4,2,1,male,returned home,<NA>,False,68,<NA>,True,False,...,False,True,False,False,False,False,False,3,<NA>,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,male,returned home,<NA>,False,40,<NA>,False,False,...,False,False,False,False,False,False,False,7,<NA>,False
1048571,1,13,male,hospitalization,False,False,51,<NA>,False,False,...,False,True,False,False,False,False,False,7,False,False
1048572,2,13,male,returned home,<NA>,False,55,<NA>,False,False,...,False,False,False,False,False,False,False,7,<NA>,False
1048573,2,13,male,returned home,<NA>,False,28,<NA>,False,False,...,False,False,False,False,False,False,False,7,<NA>,False
1048574,2,13,male,returned home,<NA>,False,52,<NA>,False,False,...,False,False,False,False,False,False,False,7,<NA>,False

In [4]:
df.dtypes

USMER                      int64
MEDICAL_UNIT               int64
SEX                     category
PATIENT_TYPE            category
INTUBED                  boolean
PNEUMONIA                boolean
AGE                        int64
PREGNANT                 boolean
DIABETES                 boolean
COPD                     boolean
ASTHMA                   boolean
INMSUPR                  boolean
HIPERTENSION             boolean
OTHER_DISEASE            boolean
CARDIOVASCULAR           boolean
OBESITY                  boolean
RENAL_CHRONIC            boolean
TOBACCO                  boolean
CLASIFFICATION_FINAL       int64
ICU                      boolean
DIED                     boolean
dtype: object

In [5]:
missing_values_count = df.isna().sum()
print(missing_values_count)

USMER                        0
MEDICAL_UNIT                 0
SEX                          0
PATIENT_TYPE                 0
INTUBED                 855869
PNEUMONIA                16003
AGE                          0
PREGNANT                527265
DIABETES                  3338
COPD                      3003
ASTHMA                    2979
INMSUPR                   3404
HIPERTENSION              3104
OTHER_DISEASE             5045
CARDIOVASCULAR            3076
OBESITY                   3032
RENAL_CHRONIC             3006
TOBACCO                   3220
CLASIFFICATION_FINAL         0
ICU                     856032
DIED                         0
dtype: int64